@Library('myPlaygrouLibrary') _
pipeline {
    agent any
    stages {
        stage('Use Advanced Function') {
            steps {
                printMessage('Hello from Advanced Shared Library!')
            }
        }
    }
}
